build:
	dotnet build
clean:
	dotnet clean
restore:
	dotnet restore
watch:
	dotnet watch --project FShRunner/FShRunner.fsproj run
start:
	dotnet run --project FShRunner/FShRunner.fsproj 0 ${d}
test:
	dotnet run --project FShRunner/FShRunner.fsproj 1 ${d} 